### ISSUE TITLE
i can't install it using npm.. it's seems get a http 404 from npmjs.org

### ISSUE THREAD

**Issue by wutitoudi** [vhpoet/grunt-jade-l10n-extractor#1]
npm install grunt-jade-l10n-extractor
npm WARN package.json webpack@0.10.0 No repository field.
npm http GET https://registry.npmjs.org/grunt-jade-l10n-extractor
npm http 304 https://registry.npmjs.org/grunt-jade-l10n-extractor
npm http GET https://registry.npmjs.org/grunt-jade-l10n-extractor/-/grunt-jade-l10n-extractor-0.1.3.tgz
npm http 404 https://registry.npmjs.org/grunt-jade-l10n-extractor/-/grunt-jade-l10n-extractor-0.1.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/grunt-jade-l10n-extractor/-/grunt-jade-l10n-extractor-0.1.3.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/isaacs/npm/issues

npm ERR! System Linux 3.2.0-29-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "grunt-jade-l10n-extractor"
npm ERR! cwd /home/dev-lib/ripple-client-cn
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dev-lib/ripple-client-cn/npm-debug.log
npm ERR! not ok code 0

**Comment by wutitoudi** [comment]
it's solved by first git clone, put it to path where want, and run npm install
